ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.store, name="store"),

    path('cart/', views.cart, name="cart"),

    path('checkout/', views.checkout, name="checkout"),

    path('update_item/', views.update_item, name="update_item"),

    path('process_order/', views.process_order, name="process_order"),

    path('register/', views.register_user, name="register"),

    path('login/', views.login_user, name="login"),

    path('logout/', views.logout_user, name="logout"),

    path('view/<int:pk>', views.product_view, name="view"),

    path('search/', views.search, name="search"),

    path('category/<int:pk>', views.category_filter, name="category"),

    path('ratings/<int:num>', views.ratings_filter, name="ratings"),

    path("contact", views.contact, name="contact"),

    path("about", views.about, name="about"),

]

store/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Avg


class Customer(models.Model):
    user = models.OneToOneField(
        User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.name


class Categories(models.Model):
    product_choices = (
        ('Automotive Parts & Accessories', 'Automotive Parts & Accessories'),
        ('Electronics', 'Electronics'),
        ('Clothing', 'Clothing'),
        ('Cosmetics', 'Cosmetics'),
        ('Toys & Games', 'Toys & Games'),
        ('Video Games', 'Video Games'),
        ('Tobacco, Pipes & Accessories', 'Tobacco, Pipes & Accessories'),
        ('Other', 'Other'),
    )
    product_category = models.CharField(
        choices=product_choices, null=True, blank=True, max_length=100)

    def __str__(self):
        return f"{self.id} : {self.get_product_category_display()}"


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=True)
    featured = models.ImageField(null=True, blank=True, upload_to='products')

    product_category = models.ForeignKey(
        Categories, on_delete=models.CASCADE)
    product_description1 = models.TextField(null=True, blank=True)
    product_description2 = models.TextField(null=True, blank=True)

    avg_rating = models.IntegerField(default=1,
                                     validators=[MinValueValidator(1), MaxValueValidator(5)])

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            return self.featured.url
        except:
            return ''

    def save(self, *args, **kwargs):
        ratings = Rating.objects.filter(product=self)
        self.avg_rating = ratings.aggregate(Avg('stars'))['stars__avg'] or 0
        super().save(*args, **kwargs)


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"{self.id} : {self.transaction_id} : {self.customer.name}"

    @property
    def shipping(self):
        shipping = False
        order_items = self.orderitem_set.all()
        for i in order_items:
            if not i.product.digital:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        order_items = self.orderitem_set.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def get_cart_items(self):
        order_items = self.orderitem_set.all()
        total = sum([item.quantity for item in order_items])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.id} : {self.order.transaction_id} : {self.product.name}"

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zip_code = models.CharField(max_length=200, null=False)
    country = models.CharField(max_length=100, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address


class Image(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images')

    @property
    def ProductimageURL(self):
        try:
            return self.image.url
        except:
            return ''


class Rating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stars = models.IntegerField(default=1,
                                validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return str(self.product) + "---" + str(self.user)

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

store/views.py
from django.shortcuts import render, redirect
import datetime
import json
from decimal import Decimal

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.mail import EmailMultiAlternatives
from django.core.mail import send_mail, BadHeaderError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_protect

from .forms import *
from .models import *
from .utils import cartData, guestOrder


@csrf_protect
def register_user(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')

            messages.success(
                request, 'Account created successfully for ' + user)

            new_user = User.objects.get(username=user)
            Customer.objects.create(user=new_user,
                                    name=new_user.username,
                                    email=new_user.email)
            print("Successfully registered")

            return redirect('login')
    context = {'form': form}
    return render(request, 'register.html', context)


@csrf_protect
def login_user(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('store')
        else:
            messages.info(
                request, 'Username or password is incorrect, Please Try Again!')

    context = {}
    return render(request, 'login.html', context)


@csrf_protect
def logout_user(request):
    logout(request)
    return redirect('store')


def store(request):

    data = cartData(request)
    cart_items = data['cartItems']

    products = Product.objects.all().order_by('created_at')
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 9)

    categories = Categories.objects.all()

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {'products': products,
               'cartItems': cart_items,
               'categories': categories}

    return render(request, 'store.html', context)


def cart(request):

    data = cartData(request)
    cart_items = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'cart.html', context)


def checkout(request):

    data = cartData(request)
    cart_items = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'checkout.html', context)


def update_item(request):

    data = json.loads(request.body)
    product_id = data['productId']
    action = data['action']

    customer = request.user.customer

    product = Product.objects.get(id=product_id)

    order, created = Order.objects.get_or_create(
        customer=customer, complete=False)

    order_item, created = OrderItem.objects.get_or_create(
        order=order, product=product)

    if action == 'add':
        order_item.quantity = (order_item.quantity + 1)
    elif action == 'remove':
        order_item.quantity = (order_item.quantity - 1)

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse('Item was added!', safe=False)


def process_order(request):

    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)

        order_items = order.orderitem_set.all()
        products = []
        try:
            email_template = render_to_string('email.html',
                                              {"name": customer.name,
                                               "product": [products.append(item.product.name for item in order_items)]})
            send = EmailMultiAlternatives(
                "Thank you for your Order",
                "Order Confirmation From HantaStore",
                settings.EMAIL_HOST_USER,
                [customer.email],
            )
            send.attach_alternative(email_template, 'text/html')
            send.send()
        except Exception as e:
            print(str(e))
            pass
    else:
        customer, order = guestOrder(request, data)
    total = Decimal(data['form']['total'])
    order.transaction_id = transaction_id
    if total == order.get_cart_total:
        order.complete = True
        order.save()
    else:
        return ValueError('Error in Total Calculation')
    if order.shipping:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            country=data['shipping']['country'],
            zip_code=data['shipping']['zip_code'],
        )
    return JsonResponse('Payment Complete!', safe=False)


def product_view(request, pk):
    product = Product.objects.get(pk=pk)
    data = cartData(request)
    cart_items = data['cartItems']
    context = {'product': product, 'cartItems': cart_items}
    return render(request, 'view.html', context)


def search(request):
    data = cartData(request)
    cart_items = data['cartItems']
    q = request.GET['q']
    products = Product.objects.filter(name__icontains=q).order_by('created_at')
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 9)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {'products': products, 'cartItems': cart_items}
    return render(request, 'search.html', context)


def category_filter(request, pk):
    product_category = Categories.objects.get(pk=pk)
    products = Product.objects.filter(
        product_category=product_category).order_by('created_at')
    data = cartData(request)
    cart_items = data['cartItems']
    categories = Categories.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 9)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {'products': products,
               'cartItems': cart_items, 'categories': categories, 'FilterCat': product_category}
    return render(request, 'category.html', context)


def ratings_filter(request, num):

    products = Product.objects.filter(
        avg_rating=num).order_by('created_at')

    product_first = products.first()

    data = cartData(request)
    cart_items = data['cartItems']

    categories = Categories.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(products, 9)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {'products': products,
               'cartItems': cart_items,
               'categories': categories,
               "product_first": product_first}

    return render(request, 'ratings.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'po0janhunt@gmail.com',
                          ['po0janhunt@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect("store")

    form = ContactForm()
    return render(request, "contact.html", {'form': form})


def about(request):
    context = {}
    return render(request, 'about.html', context)

store/templates/about.html
{% load static %}

<head>
    <title>About Us Section Design</title>

    <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>
    <link rel='preload' as='style'
        href='https://fonts.googleapis.com/css2?family=Open+Sans|Roboto:wght@300&display=swap'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Open+Sans|Roboto:wght@700&display=swap'>
</head>

<style>
    * {
        padding: 0;
        margin: 0;
        font-family: 'Josefin Sans', sans-serif;
        box-sizing: border-box;
    }

    .about {
        width: 100%;
        padding: 78px 0px;
        background-color: #191919;
    }

    .about img {
        height: auto;
        width: 420px;
    }

    .about-text {
        width: 550px;
    }

    .main {
        width: 1130px;
        max-width: 95%;
        margin: 0 auto;
        display: flex;
        align-items: center;
        justify-content: space-around;
    }

    .about-text h1 {
        color: white;
        font-size: 80px;
        text-transform: capitalize;
        margin-bottom: 20px;
    }

    .about-text h5 {
        color: white;
        font-size: 25px;
        margin-bottom: 25px;
        letter-spacing: 2px;
    }

    .about-text h5 a {
        color: #f9004d;

    }

    span {
        color: #f9004d;
    }

    .about-text p {
        color: #fcfcfc;
        letter-spacing: 1px;
        line-height: 28px;
        font-size: 18px;
        margin-bottom: 45px;
    }

    button {
        background: #f9004d;
        color: white;
        text-decoration: none;
        border: 2px solid transparent;
        font-weight: bold;
        padding: 13px 30px;
        border-radius: 30px;
        transition: .4s;
        justify-content: space-between;
    }

    button a {
        color: white;
        text-decoration: none;
        border: 2px solid transparent;
        font-weight: bold;
        transition: .4s;
        justify-content: space-between;
    }

    button:hover {
        background: transparent;
        border: 2px solid #f9004d;
        cursor: pointer;
    }
</style>

<body>
    <section class="about">
        <div class="main">
            <img src="{% static 'images/me.jpg' %}">
            <div class="about-text">
                <h1>About Me</h1>
                <h5>Developer & <a>Designer</a></h5>
                <p>Thank you very much for visiting my site. The name "HantaStore" is referenced to my friend circle
                    "Hantakaliz", bunch of doofus friends who enjoy eating and playing, and who support me all the time.
                </p>
                <p>This is one of my personal projects I did on my free time, Feel free to contact me for any problems
                    or work enquiries!
                </p>
                <button type="button"><a href="{% url 'contact' %}">Let's Talk &nbsp;</a></button>
                <button type="button"><a href="{% url 'store' %}">&nbsp; Return To Home</a></button>

            </div>
        </div>
    </section>

</body>

store/templates/cart.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<style>
    .btn-success:hover {
        color: whitesmoke;
        background-color: #212121;
        height: 100%;

    }
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190;Continue Shopping</a>

            <br>
            <br>
            <table class="table">
                <tr>
                    <th>
                        <h5>Items: <strong>{{order.get_cart_items}}</strong></h5>
                    </th>
                    <th>
                        <h5>Total: <strong>${{order.get_cart_total}}</strong></h5>
                    </th>
                    <th>
                        <a style="float:right; margin:5px" class="btn btn-success"
                            href="{% url 'checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>
        <div class="box-element-cart">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">{{item.product.name}}</div>
                <div style="flex:1">${{item.product.price|floatformat:2}}</div>
                <div style="flex:1">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart"
                            src="{% static  'images/arrow-up.png' %}">

                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart"
                            src="{% static  'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1">${{item.get_total}}</div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content%}

store/templates/contact.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<style>
    /* Style inputs with type="text", select elements and textareas */
    input[type=text],
    select,
    textarea {
        width: 100%;
        /* Full width */
        padding: 12px;
        /* Some padding */
        border: 1px solid #ccc;
        /* Gray border */
        border-radius: 4px;
        /* Rounded borders */
        box-sizing: border-box;
        /* Make sure that padding and width stays in place */
        margin-top: 6px;
        /* Add a top margin */
        margin-bottom: 16px;
        /* Bottom margin */
        resize: vertical
            /* Allow the user to vertically resize the textarea (not horizontally) */
    }

    /* Style the submit button with a specific background color etc */
    input[type=submit] {
        background-color: #04AA6D;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    /* When moving the mouse over the submit button, add a darker green color */
    input[type=submit]:hover {
        background-color: #45a049;
    }

    /* Add a background color and some padding around the form */
    .container {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>
<!--Contact form-->
<div style="margin:80px">
    <h1>Contact</h1>
    <br>
    <h4>Contact us directly if you have any questions</h4>
    <br>
    <p>
        Please write your name, email address and a message below if you have any questions.
        One of our staff members will be happy to contact you directly and answer your questions as soon as possible.
    </p>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
</div>


{% endblock %}

store/templates/view.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    .box-title {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    #feature {
        max-width: 500px;
        max-height: 600px;
        object-fit: cover;
        cursor: pointer;
        border: 2px solid black;

    }

    .featured {
        object-fit: cover;
        max-width: 180px;
        max-height: 100px;
        cursor: pointer;
        opacity: 0.5;
        margin: 5px;
        border: 2px solid black;

    }

    .featured:hover {
        opacity: 1;
    }

    .active {
        opacity: 1;
    }

    #slide-wrapper {
        max-width: 500px;
        display: flex;
        min-height: 100px;
        align-items: center;
    }

    #slider {
        width: 440px;
        display: flex;
        flex-wrap: nowrap;
        overflow-x: hidden;

    }

    #slider {
        width: 440px;
        display: flex;
        flex-wrap: nowrap;
        overflow-x: auto;


    }

    #slider::-webkit-scrollbar {
        width: 8px;

    }

    #slider::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);

    }

    #slider::-webkit-scrollbar-thumb {
        background-color: #dede2e;
        outline: 1px solid slategrey;
        border-radius: 100px;

    }

    #slider::-webkit-scrollbar-thumb:hover {
        background-color: #18b5ce;
    }

    .arrow {
        width: 30px;
        height: 30px;
        cursor: pointer;
        transition: .3s;
    }

    .arrow:hover {
        opacity: .5;
        width: 35px;
        height: 35px;
    }

    .column {
        display: flex;
        align-items: left;
        justify-content: left;
    }

    .product-title {
        display: flex;
        margin-left: 350px;
        margin-top: -230px;
    }

    .product {
        display: flex;
        margin-right: 420px;
    }

    .btn {
        padding: 10px;

    }

    .pricing {

        margin-left: 100px;
        margin-top: 10px;
        margin-right: -285px;
    }

    .product-category {
        display: flex;
        margin-left: 350px;
        margin-top: -80px;
    }

    .product-description {
        display: flex;
        margin-left: 350px;
        margin-top: 10px;
        font-weight: 300;
    }

    .checked {
        color: orange;
    }

    .product-ratings {
        padding: 20px;
        margin-left: 750px;
        margin-top: 20px;
    }

    .c-footer {
        padding: 40px;
        margin-left: 120px;
        margin-top: -80px;

    }

    .c-facebook {w
        margin-right: 10px;
    }

    .c-twitter {
        margin-right: 0px;
    }

    .c-linkedin {
        margin-right: 10px;
    }
</style>


<div style="width: 100%; float:left">
    <div class="col-lg-4">

        <img class="thumbnail" id="feature" src="{{product.imageURL}}">

        <div id="slide-wrapper">
            <img id="slideLeft" class="arrow" src="{% static 'images/arrow-left.png' %}">

            <div id="slider">
                <img class="featured" id="featured-id" src="{{product.imageURL}}">

                {% for image in product.image_set.all%}

                <img class="featured" id="featured-id" src="{{image.ProductimageURL}}">

                {% endfor %}
            </div>

            <img id="slideRight" class="arrow" src="{% static 'images/arrow-right.png' %}">
        </div>

    </div>
    <div style="height: 100px;">
        <div class="product-title">
            <h6 class="product-title"><strong>{{product.name}}</strong></h6>
        </div>
        <div class="product-category">
            <h6 class="product-category">Category:<strong>{{product.product_category.product_category}}</strong></h6>
        </div>
        <div class="product-description">
            <h6 class="product-description">{{product.product_description1}}</h6>
        </div>
        <div class="product-description">
            <h6 class="product-description">{{product.product_description2}}</h6>
        </div>

        <div class="product-ratings">
            {% if product.avg_rating == 1 %}
            <span><strong>Ratings: &nbsp; </strong></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            {% elif product.avg_rating == 2 %}
            <span><strong>Ratings: &nbsp; </strong></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            {% elif product.avg_rating == 3 %}
            <span><strong>Ratings: &nbsp; </strong></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span>
            {% elif product.avg_rating == 4 %}
            <span><strong>Ratings: &nbsp; </strong></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            {% elif product.avg_rating == 5 %}
            <span><strong>Ratings: &nbsp; </strong></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            {% endif %}
        </div>

        <div class="product">
            <hr>
            <button data-product={{product.id}} data-action="add"
                class="btn btn-outline-secondary add-btn update-cart">Add
                to Cart</button>
            <h4 style="display: inline-block; float: right" class="pricing">${{product.price|floatformat:2}}</h4>
        </div>
        <br>
        <p>Share this product :
        </p>
        <div class="c-footer">
            <a href='https://www.facebook.com/sharer.php?u={{ request.build_absolute_uri }}' target='_blank'
                rel="noreferrer" class='c-facebook'>
                <img src="{% static 'images/fb.png' %}" alt="Facebook" height="20" width="20" />
            </a>
            <a href='https://twitter.com/intent/tweet
?url={{ request.build_absolute_uri }}' target='_blank' rel="noreferrer" class='c-twitter'>
                <img src="{% static 'images/twitter.png' %}" alt="Twitter" height="20" width="20" />
            </a>
            <a href='https://www.linkedin.com/sharing/share-offsite/
?url={{ request.build_absolute_uri }}' target='_blank' rel="noreferrer" class='c-linkedin'>
                <img src="{% static 'images/linkedin.png' %}" alt="LinkedIn" height="20" width="20" />
            </a>
        </div>
    </div>
</div>


<script type="text/javascript">
    let thumbnails = document.getElementsByClassName('featured')
    let activeImages = document.getElementsByClassName('active')
    for (var i = 0; i < thumbnails.length; i++) {
        thumbnails[i].addEventListener('mouseover', function () {

            if (activeImages.length > 0) {
                activeImages[0].classList.remove('active')
            }

            this.classList.add('active')
            document.getElementById('feature').src = this.src

        })


    }

    const buttonRight = document.getElementById('slideRight');
    const buttonLeft = document.getElementById('slideLeft');


    buttonRight.addEventListener('click', function () {
        document.getElementById('slider').scrollLeft += 180;
    })



    buttonLeft.addEventListener('click', function () {
        document.getElementById('slider').scrollLeft -= 180;
    })

</script>
{% endblock %}